### ISSUE TITLE
Named route not found

### ISSUE THREAD

**Issue by jesders** [tightenco/tallstack#6]
Out of the box, there is not a named route set for the welcome route in web.php.

This throws the following error:

https://flareapp.io/share/xmNAj350

**Comment by mattstauffer** [comment]
@jesders How were you able to trigger this error?

**Comment by jesders** [comment]
`laravel new app`
`composer install`
`composer require livewire/livewire laravel-frontend-presets/tall`
`php artisan ui tall`
`npm install`
`npm run dev`

I can put in a pull request if needed. My fix was,

```
Route::get('/', function () {
    return 'welcome';
})->name('home');
```

**Comment by mattstauffer** [comment]
Ahh, wrong repo. You're looking for https://github.com/laravel-frontend-presets/tall
