### ISSUE TITLE
Not really an issue but I don't find another way to contact....

### ISSUE THREAD

**Issue by maxbertinetti** [tightenco/tallstack#7]
I'm working on an italian translation of tallstack.dev where I also want to put a blog with other content in italian, actually hosted to
https://kind-hawking-f6f4cf.netlify.app/ but I want to move on tallstack.it

I leave all reference to tallstack.dev. I want you to tell me if it is ok for you before move the content and open to the public.

**Comment by mattstauffer** [comment]
I think the one thing I would be concerned with is the blog; what do you plan to put there?

Translating the home page is fine, though!

**Comment by maxbertinetti** [comment]
The first article is about configuring a TALL project professionally on
PhpStorm with debug toolbar and so on (in Italian).

Other may follow if the site is a success (creating a component library
etc.) and there is a demand.

If you are concerned about the different content from the original site I
publish this one only with the translation and then I can write a blog on
another domain.

**Comment by mattstauffer** [comment]
@maxbertinetti I think that would be a nice idea for now (moving it to a different domain). Thanks!

**Comment by maxbertinetti** [comment]
Sorry for not responding sooner...I go online with same site (only changed theme from Green to Blu....sorry I don't like green at all!) www.tallstack.it

**Comment by mattstauffer** [comment]
@maxbertinetti No worries! Looks great!
